import { trackSelfDescribingEvent, CommonEventProperties, SelfDescribingJson } from '@snowplow/browser-tracker';
// Automatically generated by Snowtype

/**
 * Credit Boost Step event for Leo's Credit Bureau.
 */
export type CreditBoostStep = {
    /**
     * The step number
     */
    step_number: number;
}

/**
 * Creates a Snowplow Event Specification entity.
 */
export function createEventSpecification(eventSpecification: EventSpecification){
    return {
        schema:
            'iglu:com.snowplowanalytics.snowplow/event_specification/jsonschema/1-0-3',
        data: eventSpecification,
    }
}

/**
 * Automatically attached context for event specifications
 */
interface EventSpecification {
    id: string;
    name: string;
    data_product_id: string;
    data_product_name: string;
    data_product_domain: string;
}

type ContextsOrTimestamp<T = any> = Omit<CommonEventProperties<T>, 'context'> & { context?: SelfDescribingJson<T>[] | null | undefined }
/**
 * Track a Snowplow event for CreditBoostStep.
 * Credit Boost Step event for Leo&#x27;s Credit Bureau.
 */
export function trackCreditBoostStep<T extends {} = any>(creditBoostStep: CreditBoostStep & ContextsOrTimestamp<T>, trackers?: string[]){
    const { context, timestamp, ...data } = creditBoostStep;
    const event: SelfDescribingJson = {
        schema: 'iglu:com.leoscreditbureau/credit_boost_step/jsonschema/1-0-0',
        data
    };

    trackSelfDescribingEvent({
        event,
        context,
        timestamp,
    }, trackers);
}

/**
 * Creates a Snowplow CreditBoostStep entity.
 */
export function createCreditBoostStep(creditBoostStep: CreditBoostStep){
    return {
        schema: 'iglu:com.leoscreditbureau/credit_boost_step/jsonschema/1-0-0',
        data: creditBoostStep
    }
}

/**
 * Tracks a CreditBoostStep event specification.
 * ID: 96cdcf40-202b-4059-b4ed-4e6020c99d0f
 */
export function trackCreditBoostStepSpec(creditBoostStep: CreditBoostStep & ContextsOrTimestamp, trackers?: string[]){
    const eventSpecificationContext: SelfDescribingJson<EventSpecification> = createEventSpecification({ 
        id: '96cdcf40-202b-4059-b4ed-4e6020c99d0f',
        name: 'Credit Boost Step',
        data_product_id: '160e06fd-c5c9-4ef4-a13a-eb9154c35ba5',
        data_product_name: 'Leo&#x27;s Credit Bureau Data Product',
        data_product_domain: 'Credit Bureau'
    });

    const context = Array.isArray(creditBoostStep.context)
        ? [...creditBoostStep.context, eventSpecificationContext]
        : [eventSpecificationContext];

    const modifiedCreditBoostStep = {
        ...creditBoostStep,
        context,
    };

    trackCreditBoostStep<Record<string, unknown> | EventSpecification>(modifiedCreditBoostStep, trackers);
}


