/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IdentityProtectionRouteImport } from './routes/identity-protection'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CreditReportRouteImport } from './routes/credit-report'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ScoreBoostIndexRouteImport } from './routes/score-boost/index'
import { Route as ScoreBoostStep3RouteImport } from './routes/score-boost/step-3'
import { Route as ScoreBoostStep2RouteImport } from './routes/score-boost/step-2'
import { Route as ScoreBoostStep1RouteImport } from './routes/score-boost/step-1'
import { Route as ScoreBoostConclusionRouteImport } from './routes/score-boost/conclusion'
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo/start.server-funcs'
import { Route as DemoStartApiRequestRouteImport } from './routes/demo/start.api-request'
import { Route as DemoApiNamesRouteImport } from './routes/demo/api.names'
import { Route as DemoStartSsrIndexRouteImport } from './routes/demo/start.ssr.index'
import { Route as DemoStartSsrSpaModeRouteImport } from './routes/demo/start.ssr.spa-mode'
import { Route as DemoStartSsrFullSsrRouteImport } from './routes/demo/start.ssr.full-ssr'
import { Route as DemoStartSsrDataOnlyRouteImport } from './routes/demo/start.ssr.data-only'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IdentityProtectionRoute = IdentityProtectionRouteImport.update({
  id: '/identity-protection',
  path: '/identity-protection',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditReportRoute = CreditReportRouteImport.update({
  id: '/credit-report',
  path: '/credit-report',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoreBoostIndexRoute = ScoreBoostIndexRouteImport.update({
  id: '/score-boost/',
  path: '/score-boost/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoreBoostStep3Route = ScoreBoostStep3RouteImport.update({
  id: '/score-boost/step-3',
  path: '/score-boost/step-3',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoreBoostStep2Route = ScoreBoostStep2RouteImport.update({
  id: '/score-boost/step-2',
  path: '/score-boost/step-2',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoreBoostStep1Route = ScoreBoostStep1RouteImport.update({
  id: '/score-boost/step-1',
  path: '/score-boost/step-1',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoreBoostConclusionRoute = ScoreBoostConclusionRouteImport.update({
  id: '/score-boost/conclusion',
  path: '/score-boost/conclusion',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartApiRequestRoute = DemoStartApiRequestRouteImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiNamesRoute = DemoApiNamesRouteImport.update({
  id: '/demo/api/names',
  path: '/demo/api/names',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrIndexRoute = DemoStartSsrIndexRouteImport.update({
  id: '/demo/start/ssr/',
  path: '/demo/start/ssr/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrSpaModeRoute = DemoStartSsrSpaModeRouteImport.update({
  id: '/demo/start/ssr/spa-mode',
  path: '/demo/start/ssr/spa-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrFullSsrRoute = DemoStartSsrFullSsrRouteImport.update({
  id: '/demo/start/ssr/full-ssr',
  path: '/demo/start/ssr/full-ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrDataOnlyRoute = DemoStartSsrDataOnlyRouteImport.update({
  id: '/demo/start/ssr/data-only',
  path: '/demo/start/ssr/data-only',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/credit-report': typeof CreditReportRoute
  '/dashboard': typeof DashboardRoute
  '/identity-protection': typeof IdentityProtectionRoute
  '/login': typeof LoginRoute
  '/score-boost/conclusion': typeof ScoreBoostConclusionRoute
  '/score-boost/step-1': typeof ScoreBoostStep1Route
  '/score-boost/step-2': typeof ScoreBoostStep2Route
  '/score-boost/step-3': typeof ScoreBoostStep3Route
  '/score-boost': typeof ScoreBoostIndexRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/credit-report': typeof CreditReportRoute
  '/dashboard': typeof DashboardRoute
  '/identity-protection': typeof IdentityProtectionRoute
  '/login': typeof LoginRoute
  '/score-boost/conclusion': typeof ScoreBoostConclusionRoute
  '/score-boost/step-1': typeof ScoreBoostStep1Route
  '/score-boost/step-2': typeof ScoreBoostStep2Route
  '/score-boost/step-3': typeof ScoreBoostStep3Route
  '/score-boost': typeof ScoreBoostIndexRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/credit-report': typeof CreditReportRoute
  '/dashboard': typeof DashboardRoute
  '/identity-protection': typeof IdentityProtectionRoute
  '/login': typeof LoginRoute
  '/score-boost/conclusion': typeof ScoreBoostConclusionRoute
  '/score-boost/step-1': typeof ScoreBoostStep1Route
  '/score-boost/step-2': typeof ScoreBoostStep2Route
  '/score-boost/step-3': typeof ScoreBoostStep3Route
  '/score-boost/': typeof ScoreBoostIndexRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/credit-report'
    | '/dashboard'
    | '/identity-protection'
    | '/login'
    | '/score-boost/conclusion'
    | '/score-boost/step-1'
    | '/score-boost/step-2'
    | '/score-boost/step-3'
    | '/score-boost'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/credit-report'
    | '/dashboard'
    | '/identity-protection'
    | '/login'
    | '/score-boost/conclusion'
    | '/score-boost/step-1'
    | '/score-boost/step-2'
    | '/score-boost/step-3'
    | '/score-boost'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  id:
    | '__root__'
    | '/'
    | '/credit-report'
    | '/dashboard'
    | '/identity-protection'
    | '/login'
    | '/score-boost/conclusion'
    | '/score-boost/step-1'
    | '/score-boost/step-2'
    | '/score-boost/step-3'
    | '/score-boost/'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreditReportRoute: typeof CreditReportRoute
  DashboardRoute: typeof DashboardRoute
  IdentityProtectionRoute: typeof IdentityProtectionRoute
  LoginRoute: typeof LoginRoute
  ScoreBoostConclusionRoute: typeof ScoreBoostConclusionRoute
  ScoreBoostStep1Route: typeof ScoreBoostStep1Route
  ScoreBoostStep2Route: typeof ScoreBoostStep2Route
  ScoreBoostStep3Route: typeof ScoreBoostStep3Route
  ScoreBoostIndexRoute: typeof ScoreBoostIndexRoute
  DemoApiNamesRoute: typeof DemoApiNamesRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
  DemoStartSsrDataOnlyRoute: typeof DemoStartSsrDataOnlyRoute
  DemoStartSsrFullSsrRoute: typeof DemoStartSsrFullSsrRoute
  DemoStartSsrSpaModeRoute: typeof DemoStartSsrSpaModeRoute
  DemoStartSsrIndexRoute: typeof DemoStartSsrIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/identity-protection': {
      id: '/identity-protection'
      path: '/identity-protection'
      fullPath: '/identity-protection'
      preLoaderRoute: typeof IdentityProtectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credit-report': {
      id: '/credit-report'
      path: '/credit-report'
      fullPath: '/credit-report'
      preLoaderRoute: typeof CreditReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/score-boost/': {
      id: '/score-boost/'
      path: '/score-boost'
      fullPath: '/score-boost'
      preLoaderRoute: typeof ScoreBoostIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/score-boost/step-3': {
      id: '/score-boost/step-3'
      path: '/score-boost/step-3'
      fullPath: '/score-boost/step-3'
      preLoaderRoute: typeof ScoreBoostStep3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/score-boost/step-2': {
      id: '/score-boost/step-2'
      path: '/score-boost/step-2'
      fullPath: '/score-boost/step-2'
      preLoaderRoute: typeof ScoreBoostStep2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/score-boost/step-1': {
      id: '/score-boost/step-1'
      path: '/score-boost/step-1'
      fullPath: '/score-boost/step-1'
      preLoaderRoute: typeof ScoreBoostStep1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/score-boost/conclusion': {
      id: '/score-boost/conclusion'
      path: '/score-boost/conclusion'
      fullPath: '/score-boost/conclusion'
      preLoaderRoute: typeof ScoreBoostConclusionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/api-request': {
      id: '/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/names': {
      id: '/demo/api/names'
      path: '/demo/api/names'
      fullPath: '/demo/api/names'
      preLoaderRoute: typeof DemoApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/': {
      id: '/demo/start/ssr/'
      path: '/demo/start/ssr'
      fullPath: '/demo/start/ssr'
      preLoaderRoute: typeof DemoStartSsrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/spa-mode': {
      id: '/demo/start/ssr/spa-mode'
      path: '/demo/start/ssr/spa-mode'
      fullPath: '/demo/start/ssr/spa-mode'
      preLoaderRoute: typeof DemoStartSsrSpaModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/full-ssr': {
      id: '/demo/start/ssr/full-ssr'
      path: '/demo/start/ssr/full-ssr'
      fullPath: '/demo/start/ssr/full-ssr'
      preLoaderRoute: typeof DemoStartSsrFullSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/data-only': {
      id: '/demo/start/ssr/data-only'
      path: '/demo/start/ssr/data-only'
      fullPath: '/demo/start/ssr/data-only'
      preLoaderRoute: typeof DemoStartSsrDataOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreditReportRoute: CreditReportRoute,
  DashboardRoute: DashboardRoute,
  IdentityProtectionRoute: IdentityProtectionRoute,
  LoginRoute: LoginRoute,
  ScoreBoostConclusionRoute: ScoreBoostConclusionRoute,
  ScoreBoostStep1Route: ScoreBoostStep1Route,
  ScoreBoostStep2Route: ScoreBoostStep2Route,
  ScoreBoostStep3Route: ScoreBoostStep3Route,
  ScoreBoostIndexRoute: ScoreBoostIndexRoute,
  DemoApiNamesRoute: DemoApiNamesRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
  DemoStartSsrDataOnlyRoute: DemoStartSsrDataOnlyRoute,
  DemoStartSsrFullSsrRoute: DemoStartSsrFullSsrRoute,
  DemoStartSsrSpaModeRoute: DemoStartSsrSpaModeRoute,
  DemoStartSsrIndexRoute: DemoStartSsrIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
